name: GitHound
# This workflow is triggered on pushes to the repository.

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    paths:
      - githound/**
      - .github/workflows/githound.yaml
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
env:
  GITHUB_HASH: $(git rev-parse --short "$GITHUB_SHA")

jobs:
  buildonpush:
    name: BuildOnPush
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "Build and Push"
        echo "$GITHUB_HASH"
    - name: Login to Registry
      run: |
        echo "${DOCKER_PASSWORD}" | docker login hub.docker.com -u ${DOCKER_USERNAME} --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
