name: K8sTestTools
# This workflow is triggered on pushes to the repository.

on:
  push:
    paths:
    - ks8-test-tools/**
    - .github/workflows/ks8testtools.yaml

env:
  WORKSPACE: k8s-test-tools
  DOCKER_REPO: cloudkats
  DOCKER_IMAGE: k8s-test-tools

jobs:
  buildonpush:
    name: BuildOnPush
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      working-directory: ${{ env.WORKSPACE }}
      run: |
        echo "Build"

        docker build . --file Dockerfile --tag image \
          --build-arg K8S_VERSION=$(cat version)

    - name: Login to Registry
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

    - name: Push Docker image
      working-directory: ${{ env.WORKSPACE }}
      run: |
        echo "Push"

        image_version=$(cat version)

        docker tag image "${IMAGE_ID}:${image_version}.${tag_date}"
        docker push "${IMAGE_ID}:${image_version}.${tag_date}"

        docker tag image "${IMAGE_ID}:${image_version}"
        docker push "${IMAGE_ID}:${image_version}"

        docker tag image "${IMAGE_ID}:latest"
        docker push "${IMAGE_ID}:latest"
