name: kubectl
# This workflow is triggered on pushes to the repository.

on:
  push:
    branches: master
    paths:
    - kubectl/**
    - .github/workflows/kubectl.yaml

env:
  WORKSPACE: kubectl
  DOCKER_IMAGE: cloudkats/kubectl

jobs:
  buildonpush:
    name: BuildOnPush
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2

    - uses: brpaz/hadolint-action@v1.0.2
      env:
        XDG_CONFIG_HOME: ${{ env.WORKSPACE }}/hadolint.yaml
      with:
        dockerfile: ${{ env.WORKSPACE }}/Dockerfile

    -
      name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: Prepare
      id: prep
      working-directory: ${{ env.WORKSPACE }}
      run: |
        VERSION=$(sed -n 's/ENV VERSION=\(.*\)/\1/p' Dockerfile)

        echo ::set-output name=version::${VERSION}
        echo ::set-output name=created::$(date -u +'%Y-%m-%d')

    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ env.WORKSPACE}}/Dockefile
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ steps.prep.outputs.created }}
          ${{ env.DOCKER_IMAGE }}:${{ steps.prep.outputs.version }}
        labels: |
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.licenses=${{ github.event.repository.license.name }}

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        DOCKERHUB_REPOSITORY: ${{ env.DOCKER_IMAGE }}
