name: release
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - master

env:
  WITH_V: true
  DEFAULT_BUMP: patch
  INITIAL_VERSION: 0.0.0
  # https://github.com/chalk/supports-color/issues/106
  FORCE_COLOR: true

jobs:
  build:
    name: release new version
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '#release')"
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '10'

    - name: register values
      id: register
      run: |
        echo "::set-output name=release_timestamp::$(date +%Y-%m-%d_%H.%m)"
        echo "::set-output name=tag_hash::${GITHUB_SHA::8}"
        echo "::set-output name=changelog::$(git log -1 --pretty=format:"%s")"

    - name: bump version and push tag
      uses: anothrNick/github-tag-action@1.17.0
      id: tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: create release
      id: create_release
      uses: actions/create-release@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: release ${{ steps.version.register.release_timestamp}}
        draft: false
        prerelease: false
        body: |
          Changes in this Release ${{ steps.register.tag_hash.changelog }}
          - ${{ steps.define-version.register.changelog }}
          - Terraform Version: ${{ env.TERRAFORM_VERSION }}
          - Terragrunt Version: ${{ env.TERRAGRAUNT_VERSION }}

    - name: create release branch
      id: create_release_branch
      if: "contains(github.event.head_commit.message, 'branch')"
      uses: peterjgrainger/action-create-branch@v2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: release/${{ steps.tag.outputs.tag }}