name: terragrunt
# This workflow is triggered on pushes to the repository.

on:
  push:
    paths:
    - terragrunt/**
    - .github/workflows/terragrunt.yaml

env:
  WORKSPACE: terragrunt
  DOCKER_REPO: cloudkats
  DOCKER_IMAGE: terragrunt
  SHA8: ${GITHUB_SHA::8}

jobs:
  buildonpush:
    name: BuildOnPush
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      working-directory: ${{ env.WORKSPACE }}
      run: |
        echo "Build"
        echo ${GITHUB_SHA::8}

        docker build . --file Dockerfile --tag image \
          --build-arg TERRAFORM_VERSION=$(cat version)

    - name: Login to Registry
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

    - name: Push Docker image
      working-directory: ${{ env.WORKSPACE }}
      run: |
        echo "Push"

        tf_version=$(cat version)

        IMAGE_ID="${DOCKER_REPO}/${DOCKER_IMAGE}"
        tag_date="$(date +%Y%d%m)"

        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        docker tag image "${IMAGE_ID}:${tf_version"
        docker push "${IMAGE_ID}:${tf_version}"

        docker tag image "${IMAGE_ID}:latest"
        docker push "${IMAGE_ID}:latest"


